/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package james.rpn.calculator.app;

import org.junit.jupiter.api.Test;

class MainTest {
    @Test
    protected void appHasAGreeting() {
        final Main classUnderTest = new Main();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
