package james.rpn.calculator.app;

import java.util.Scanner;

import james.rpn.calculator.popup.PopUpPrinter;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {

    public static void main(final String[] args) {
        final Scanner scanner = new Scanner(System.in);
        final PopUpPrinter printer = new PopUpPrinter();

        printer.println("Started RPN Caculator, please type expression below:");
        try {
            while (true) {
                final String inputString = scanner.nextLine();
                printer.println("stack " + inputString);
            }
        } catch (final RuntimeException e) {
            // TODO: new Exception;
            throw new RuntimeException(e);
        } finally {
            scanner.close();
        }

    }
}
