/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package james.rpn.calculator.app;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
public class Main {
    private final Logger logger = LogManager.getLogger("Main");
    public String getGreeting() {
        logger.info("Starting RPN Caculator.");
        return "Hello world.";
    }

    public static void main(final String[] args) {
        System.out.println(new Main().getGreeting());
    }
}
